package com.tasly.deepureflow.client;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.tasly.deepureflow.domain.system.Place;
import com.tasly.deepureflow.domain.system.PlaceExample;
import com.tasly.deepureflow.domain.system.PlaceExtended;

public interface IPlaceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_area
     *
     * @mbggenerated Tue Sep 08 14:16:41 CST 2015
     */
    int countByExample(PlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_area
     *
     * @mbggenerated Tue Sep 08 14:16:41 CST 2015
     */
    int deleteByExample(PlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_area
     *
     * @mbggenerated Tue Sep 08 14:16:41 CST 2015
     */
    int deleteByPrimaryKey(String areacode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_area
     *
     * @mbggenerated Tue Sep 08 14:16:41 CST 2015
     */
    int insert(Place record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_area
     *
     * @mbggenerated Tue Sep 08 14:16:41 CST 2015
     */
    int insertSelective(Place record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_area
     *
     * @mbggenerated Tue Sep 08 14:16:41 CST 2015
     */
    List<Place> selectByExample(PlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_area
     *
     * @mbggenerated Tue Sep 08 14:16:41 CST 2015
     */
    Place selectByPrimaryKey(String areacode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_area
     *
     * @mbggenerated Tue Sep 08 14:16:41 CST 2015
     */
    int updateByExampleSelective(@Param("record") Place record, @Param("example") PlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_area
     *
     * @mbggenerated Tue Sep 08 14:16:41 CST 2015
     */
    int updateByExample(@Param("record") Place record, @Param("example") PlaceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_area
     *
     * @mbggenerated Tue Sep 08 14:16:41 CST 2015
     */
    int updateByPrimaryKeySelective(Place record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_area
     *
     * @mbggenerated Tue Sep 08 14:16:41 CST 2015
     */
    int updateByPrimaryKey(Place record);

    List<PlaceExtended> selectByExtended();
}